-- Reviewed, reproducible market segmentation for the curated catalogue.
-- Re-running preserves a manual segment already assigned to a perfume.

BEGIN;

CREATE TEMP TABLE segment_map (
    brand TEXT PRIMARY KEY,
    market_segment TEXT NOT NULL CHECK (market_segment IN ('daily', 'luxury', 'niche'))
);

INSERT INTO segment_map (brand, market_segment) VALUES
    ('A13', 'niche'),
    ('Abaton', 'niche'),
    ('Abdul Karim Al Faransi', 'niche'),
    ('Abdul Samad Al Qurashi', 'niche'),
    ('Abel', 'niche'),
    ('Abercrombie Fitch', 'daily'),
    ('Absolument Parfumeur', 'niche'),
    ('Acca Kappa', 'luxury'),
    ('Acqua Dell Elba', 'niche'),
    ('Acqua Di Portofino', 'luxury'),
    ('Adi Ale Van', 'niche'),
    ('Adopt Parfums', 'daily'),
    ('A Dozen Roses', 'niche'),
    ('Adrienne Vittadini', 'daily'),
    ('Aedes De Venustas', 'niche'),
    ('Aesop', 'luxury'),
    ('Affinessence', 'niche'),
    ('Agatha Ruiz De La Prada', 'daily'),
    ('Agatho Parfum', 'niche'),
    ('Agent Provocateur', 'luxury'),
    ('Agonist', 'niche'),
    ('Akro', 'niche'),
    ('A Lab On Fire', 'niche'),
    ('Alain Delon', 'daily'),
    ('Al Ambra', 'niche'),
    ('Alessandro Dell Acqua', 'luxury'),
    ('Alexander Mcqueen', 'luxury'),
    ('Alfred Sung', 'luxury'),
    ('Alghabra Parfums', 'niche'),
    ('Alkemia Perfumes', 'niche'),
    ('Al Rehab', 'daily'),
    ('Alvarez Gomez', 'daily'),
    ('Al Wataniah', 'daily'),
    ('Alyssa Ashley', 'daily'),
    ('Amway', 'daily'),
    ('Amyi', 'niche'),
    ('Anatole Lebreton', 'niche'),
    ('And Other Stories', 'daily'),
    ('Andrea Maack', 'niche'),
    ('Anfas', 'niche'),
    ('Angela Ciampagna', 'niche'),
    ('Angelos Creations Olfactives', 'niche'),
    ('Animale', 'daily'),
    ('Anka Kus Parfuem', 'niche'),
    ('Annayake', 'luxury'),
    ('A N Other', 'niche'),
    ('Antonio Alessandria', 'niche'),
    ('Antonio Puig', 'daily'),
    ('Antonio Visconti', 'niche'),
    ('Apivita', 'luxury'),
    ('April Aromatics', 'niche'),
    ('Aqaba', 'niche'),
    ('Aquolina', 'daily'),
    ('Arabesque Perfumes', 'niche'),
    ('Arabiyat', 'daily'),
    ('Argos', 'niche'),
    ('Armand Basi', 'luxury'),
    ('Arno Sorel', 'daily'),
    ('Arquiste', 'niche'),
    ('Arrogance', 'daily'),
    ('Arteolfatto', 'niche'),
    ('Asdaaf', 'daily'),
    ('Astrophil Stella', 'niche'),
    ('Atelier Flou', 'niche'),
    ('Atelier Materi', 'niche'),
    ('Atelier Rebul', 'niche'),
    ('Attar Collection', 'niche'),
    ('Aubusson', 'daily'),
    ('Au Pays De La Fleur D Oranger', 'niche'),
    ('Auphorie', 'niche'),
    ('Avatim', 'daily'),
    ('Axe', 'daily'),
    ('Azman', 'niche'),
    ('Badgley Mischka', 'luxury'),
    ('Bait Al Bakhoor', 'daily'),
    ('Baldinini', 'luxury'),
    ('Baruti', 'niche'),
    ('Beaufort London', 'niche'),
    ('Bebe', 'daily'),
    ('Bella Aura', 'luxury'),
    ('Benefit', 'luxury'),
    ('Beso Beach Perfumes', 'niche'),
    ('Betty Barclay', 'daily'),
    ('Bharara', 'niche'),
    ('Biehl Parfumkunstwerke', 'niche'),
    ('Bi Es', 'daily'),
    ('Bijan', 'luxury'),
    ('Bill Blass', 'luxury'),
    ('Biotherm', 'luxury'),
    ('Bjork And Berries', 'niche'),
    ('Blackbird', 'niche'),
    ('Blend Oud', 'niche'),
    ('Blood Concept', 'niche'),
    ('Body Fantasies', 'daily'),
    ('Bogue', 'niche'),
    ('Borntostandout', 'niche'),
    ('Borsari', 'niche'),
    ('Botanicae', 'niche'),
    ('Bottega Verde', 'daily'),
    ('Bourjois', 'daily'),
    ('Boy Smells', 'niche'),
    ('Brooks Brothers', 'luxury'),
    ('Bruno Acampora', 'niche'),
    ('Bruno Perrucci Parfums', 'niche'),
    ('Brut Parfums Prestige', 'daily'),
    ('Bugatti Fashion', 'luxury'),
    ('Burdin', 'niche'),
    ('Byblos', 'luxury'),
    ('Bybozo', 'niche'),
    ('Byron Parfums', 'niche'),
    ('By Rosie Jane', 'niche'),
    ('Calaj', 'niche'),
    ('Cale Fragranze D Autore', 'niche'),
    ('Calgon', 'daily'),
    ('Calypso Christiane Celle', 'luxury'),
    ('Candie S', 'daily'),
    ('Carlo Corinto', 'luxury'),
    ('Carol S Daughter', 'daily'),
    ('Castelbajac', 'luxury'),
    ('Caswell Massey', 'niche'),
    ('Caudalie', 'luxury'),
    ('Celine', 'luxury'),
    ('Celine Dion', 'daily'),
    ('Chabaud Maison De Parfum', 'niche'),
    ('Chantecaille', 'luxury'),
    ('Charriol', 'luxury'),
    ('Chevignon', 'luxury'),
    ('Chris Collins', 'niche'),
    ('Christian Lacroix', 'luxury'),
    ('Christian Louboutin', 'luxury'),
    ('Christine Darvin', 'daily'),
    ('Ciclo Cosmeticos', 'daily'),
    ('City', 'daily'),
    ('Clarins', 'luxury'),
    ('C O Bigelow', 'daily'),
    ('Collistar', 'luxury'),
    ('Conde Parfum', 'niche'),
    ('Confessions Of A Rebel', 'niche'),
    ('Coquillete', 'niche'),
    ('Coreterno', 'niche'),
    ('Cosmogony', 'niche'),
    ('Crabtree Evelyn', 'luxury'),
    ('Cra Yon', 'niche'),
    ('Cremo', 'daily'),
    ('Custo Barcelona', 'luxury'),
    ('Czech Speake', 'niche'),
    ('Dame Perfumery', 'niche'),
    ('Dana', 'daily'),
    ('Daniel Hechter', 'daily'),
    ('Daniel Josier', 'niche'),
    ('David Yurman', 'luxury'),
    ('Day Three', 'niche'),
    ('Dedcool', 'niche'),
    ('De Gabor', 'niche'),
    ('Demeter Fragrance', 'daily'),
    ('Denim', 'daily'),
    ('Desigual', 'daily'),
    ('Detaille', 'niche'),
    ('Diana Vreeland', 'niche'),
    ('Dilis Parfum', 'daily'),
    ('Dina Cosmetics', 'daily'),
    ('Divina Terra', 'niche'),
    ('Divine', 'niche'),
    ('Don Algodon', 'daily'),
    ('Dossier', 'daily'),
    ('Dries Van Noten', 'luxury'),
    ('Dsh Perfumes', 'niche'),
    ('Dumont', 'daily'),
    ('Eau Jeune', 'daily'),
    ('E Coudray', 'niche'),
    ('Eight Bob', 'niche'),
    ('El Ganso', 'daily'),
    ('Elizabeth Arden', 'daily'),
    ('Elizabeth Taylor', 'daily'),
    ('Ella K Parfums', 'niche'),
    ('Ella Mikao', 'daily'),
    ('Elle', 'daily'),
    ('Ellen Tracy', 'daily'),
    ('El Nabil', 'daily'),
    ('Emilio Pucci', 'luxury'),
    ('Emirates Pride Perfumes', 'niche'),
    ('Emper', 'daily'),
    ('Enrico Coveri', 'luxury'),
    ('Enrique Iglesias', 'daily'),
    ('Eon Productions', 'daily'),
    ('Epico', 'niche'),
    ('Erbario Toscano', 'niche'),
    ('Eric Buterbaugh Florals', 'niche'),
    ('Escentric Molecules', 'niche'),
    ('Esika', 'daily'),
    ('Esprit', 'daily'),
    ('Essence', 'daily'),
    ('Essential Parfums', 'niche'),
    ('Esse Strikes The Notes', 'niche'),
    ('Eutopie', 'niche'),
    ('Evaflor', 'daily'),
    ('Eva Longoria', 'daily'),
    ('Everlast', 'daily'),
    ('Faberge', 'daily'),
    ('Faconnable', 'luxury'),
    ('Farmacia Ss Annunziata', 'niche'),
    ('Fcuk', 'daily'),
    ('Fenjal', 'daily'),
    ('Fiilit', 'niche'),
    ('Fiorucci', 'daily'),
    ('Flavia', 'daily'),
    ('Floral Street', 'niche'),
    ('Fort Manle', 'niche'),
    ('Fragrance World', 'daily'),
    ('Francesca Bianchi', 'niche'),
    ('Francesca Dell Oro', 'niche'),
    ('Frassai', 'niche'),
    ('Fred Hayman', 'luxury'),
    ('Fugazzi', 'niche'),
    ('Furla', 'luxury'),
    ('Fzotic', 'niche'),
    ('Gabriela Sabatini', 'daily'),
    ('Gai Mattiolo', 'luxury'),
    ('Gale Hayman', 'luxury'),
    ('Galimard', 'niche'),
    ('Gallagher Fragrances', 'niche'),
    ('Gallivant', 'niche'),
    ('Gandini 1896', 'niche'),
    ('Gap', 'daily'),
    ('Gendarme', 'niche'),
    ('Geo F Trumper', 'niche'),
    ('Germaine Monteil', 'luxury'),
    ('Gianmarco Venturi', 'luxury'),
    ('Giardini Di Toscana', 'niche'),
    ('Gilles Cantuel', 'daily'),
    ('Giorgio Valenti', 'daily'),
    ('Giovanna Baby', 'daily'),
    ('Gisada', 'niche'),
    ('Gloria Vanderbilt', 'daily'),
    ('Goldfield Banks Australia', 'niche'),
    ('Grossmith', 'niche'),
    ('Guy Laroche', 'luxury'),
    ('Halston', 'luxury'),
    ('Hanae Mori', 'luxury'),
    ('Happyland', 'niche'),
    ('Harvey Prince', 'niche'),
    ('Hayari Parfums', 'niche'),
    ('Helan', 'daily'),
    ('Helena Rubinstein', 'luxury'),
    ('Henry Jacques', 'niche'),
    ('Henry Rose', 'niche'),
    ('Heretic Parfums', 'niche'),
    ('Hermetica', 'niche'),
    ('Herve Gambs Paris', 'niche'),
    ('Hilary Duff', 'daily'),
    ('Hilde Soliani', 'niche'),
    ('Hinode', 'daily'),
    ('Hiram Green', 'niche'),
    ('H M', 'daily'),
    ('House Of Bo', 'niche'),
    ('House Of Matriarch', 'niche'),
    ('Hunca', 'daily'),
    ('Id Parfums', 'daily'),
    ('Illuminum', 'niche'),
    ('Impulse', 'daily'),
    ('Ines De La Fressange', 'luxury'),
    ('Instituto Espanol', 'daily'),
    ('In The Box', 'daily'),
    ('Ivanka Trump', 'daily'),
    ('Jacques Fath', 'luxury'),
    ('Jacques Zolty', 'niche'),
    ('Jafra', 'daily'),
    ('Jardin Boheme', 'niche'),
    ('Jardin De France', 'niche'),
    ('Jardins D Ecrivains', 'niche'),
    ('Jean Charles Brosseau', 'luxury'),
    ('Jean D Albret', 'niche'),
    ('Jeanne En Provence', 'daily'),
    ('John Varvatos', 'luxury'),
    ('Jo Loves', 'niche'),
    ('Jorum Studio', 'niche'),
    ('Jousset Parfums', 'niche'),
    ('Jovan', 'daily'),
    ('Joya', 'niche'),
    ('J Scent', 'niche'),
    ('Junaid Perfumes', 'niche'),
    ('Just Jack', 'daily'),
    ('Kalina', 'daily'),
    ('Kate Spade', 'luxury'),
    ('Keiko Mecheri', 'niche'),
    ('Kensie', 'daily'),
    ('Kerosene', 'niche'),
    ('Kookai', 'daily'),
    ('Koto Parfums', 'daily'),
    ('Krizia', 'luxury'),
    ('L Acqua Di Fiori', 'daily'),
    ('Ladanika', 'niche'),
    ('La Maison De La Vanille', 'niche'),
    ('La Martina', 'luxury'),
    ('Lancaster', 'luxury'),
    ('Lancetti', 'luxury'),
    ('Laura Mercier', 'luxury'),
    ('Laurence Dumont', 'daily'),
    ('Laverne', 'niche'),
    ('Le Couvent Maison De Parfum', 'niche'),
    ('Le Galion', 'niche'),
    ('Le Labo', 'luxury'),
    ('Le Monde Gourmand', 'daily'),
    ('Les Eaux Primordiales', 'niche'),
    ('Les Indemodables', 'niche'),
    ('Les Nereides', 'luxury'),
    ('Lesquendieu', 'niche'),
    ('Les Senteurs Gourmandes', 'niche'),
    ('Lili Bermuda', 'niche'),
    ('Linn Young', 'daily'),
    ('Liu Jo', 'luxury'),
    ('Lomani', 'daily'),
    ('Louis Feraud', 'luxury'),
    ('Lpdo', 'daily'),
    ('Lr', 'daily'),
    ('L T Piver', 'niche'),
    ('Luciano Soprani', 'luxury'),
    ('Lucy B', 'niche'),
    ('Lux E Terra', 'niche'),
    ('Luxodor', 'niche'),
    ('Mac', 'luxury'),
    ('Maison Crivelli', 'niche'),
    ('Maissa Parfums', 'niche'),
    ('Majouri', 'niche'),
    ('Mandarina Duck', 'luxury'),
    ('Mango', 'daily'),
    ('Manos Gerakinis', 'niche'),
    ('Marbert', 'daily'),
    ('Marc Antoine Barrois', 'niche'),
    ('Marc De La Morandiere', 'daily'),
    ('Marc Ecko', 'daily'),
    ('Marc Joseph', 'daily'),
    ('Marilyn Miglin', 'daily'),
    ('Mark', 'daily'),
    ('Mark Buxton', 'niche'),
    ('Marks Spencer', 'daily'),
    ('Massimo Dutti', 'daily'),
    ('Maurer Wirtz', 'daily'),
    ('Max Philip', 'niche'),
    ('Mazzolari', 'niche'),
    ('Memoize London', 'niche'),
    ('Mendittorosa', 'niche'),
    ('Michael Malul London', 'luxury'),
    ('Milton Lloyd', 'daily'),
    ('Mimmina', 'daily'),
    ('Min New York', 'niche'),
    ('M Int', 'niche'),
    ('Mirko Buffini Firenze', 'niche'),
    ('Mith', 'niche'),
    ('Molton Brown', 'luxury'),
    ('Molyneux', 'luxury'),
    ('Moncler', 'luxury'),
    ('Montana', 'luxury'),
    ('Morgan', 'daily'),
    ('Morph', 'niche'),
    ('Mpf', 'niche'),
    ('Mustang', 'daily'),
    ('Myrurgia', 'daily'),
    ('Nabeel', 'daily'),
    ('Nabucco', 'niche'),
    ('Nafnaf', 'daily'),
    ('Nasomatto', 'niche'),
    ('Ne Emah For Fragrance Oudh', 'niche'),
    ('Neil Morris', 'niche'),
    ('Nejma', 'niche'),
    ('Nest', 'niche'),
    ('Nicki Minaj', 'daily'),
    ('Nike', 'daily'),
    ('Nikos', 'luxury'),
    ('Nine West', 'daily'),
    ('Nuancielo', 'daily'),
    ('Ocean Pacific', 'daily'),
    ('O Driu', 'niche'),
    ('Ojar', 'niche'),
    ('Olympic Orchids Artisan Perfumes', 'niche'),
    ('Omnia Profumi', 'niche'),
    ('One Day', 'niche'),
    ('Orientica', 'daily'),
    ('Orientica Premium', 'niche'),
    ('Orlov Paris', 'niche'),
    ('Orto Parisi', 'niche'),
    ('Otto Kern', 'daily'),
    ('Pacha Ibiza', 'daily'),
    ('Pacifica', 'daily'),
    ('Pacoma', 'daily'),
    ('Paloma Picasso', 'luxury'),
    ('Panouge', 'niche'),
    ('Parfum Satori', 'niche'),
    ('Parfums Berdoues', 'niche'),
    ('Parfums De Coeur', 'daily'),
    ('Parfums Et Senteurs Du Pays Basque', 'niche'),
    ('Parfums Sophiste', 'niche'),
    ('Parfums Vintage', 'daily'),
    ('Paris Corner', 'daily'),
    ('Pascal Morabito', 'luxury'),
    ('Patrice Martin', 'niche'),
    ('Paul Joe', 'luxury'),
    ('Perfumer S Workshop', 'daily'),
    ('Phaedon', 'niche'),
    ('Philosophy', 'luxury'),
    ('Pierre Cardin', 'luxury'),
    ('Pinrose', 'niche'),
    ('Pokrovka Trading House', 'niche'),
    ('Prince Matchabelli', 'daily'),
    ('Proad', 'daily'),
    ('Profumi Del Forte', 'niche'),
    ('Profumum Roma', 'niche'),
    ('Pull Bear', 'daily'),
    ('Pupa', 'daily'),
    ('Quem Disse Berenice', 'daily'),
    ('Rammstein', 'daily'),
    ('Ramon Monegal', 'niche'),
    ('Rania J', 'niche'),
    ('Regalien', 'niche'),
    ('Regime Des Fleurs', 'niche'),
    ('Reine De Saba', 'niche'),
    ('Remy Latour', 'daily'),
    ('Renier Perfumes', 'niche'),
    ('Replay', 'daily'),
    ('Revlon', 'daily'),
    ('Reyane Tradition', 'daily'),
    ('Rituals', 'luxury'),
    ('Roads', 'niche'),
    ('Roberto Capucci', 'luxury'),
    ('Roberto Verino', 'luxury'),
    ('Roccobarocco', 'luxury'),
    ('Rogue Perfumery', 'niche'),
    ('Rook Perfumes', 'niche'),
    ('Roos Roos', 'niche'),
    ('Rosendo Mateu Olfactive Expressions', 'niche'),
    ('Rue21', 'daily'),
    ('Samy Andraus Fragrances', 'niche'),
    ('Sapil', 'daily'),
    ('Sarantis', 'daily'),
    ('Selena Gomez', 'daily'),
    ('Simone Andreoli', 'niche'),
    ('Skylar', 'niche'),
    ('Slava Zaitsev', 'luxury'),
    ('Smell Bent', 'niche'),
    ('Snif', 'niche'),
    ('So', 'daily'),
    ('Sol De Janeiro', 'daily'),
    ('Solinotes', 'daily'),
    ('S Oliver', 'daily'),
    ('Spirit Of Kings', 'niche'),
    ('Stella Mccartney', 'luxury'),
    ('Sultan Pasha Attars', 'niche'),
    ('Superz', 'niche'),
    ('Swarovski', 'luxury'),
    ('Swedoft', 'niche'),
    ('Tartine Et Chocolat', 'luxury'),
    ('Ted Baker', 'luxury'),
    ('Terry De Gunzburg', 'luxury'),
    ('The 7 Virtues', 'niche'),
    ('The Dua Brand', 'daily'),
    ('The Gate Fragrances Paris', 'niche'),
    ('Theodoros Kalotinis', 'niche'),
    ('The Spirit Of Dubai', 'niche'),
    ('The Woods Collection', 'niche'),
    ('Thomas Kosmala', 'niche'),
    ('Tiffany', 'luxury'),
    ('Tom Tailor', 'daily'),
    ('Tonatto Profumi', 'niche'),
    ('Toni Gard', 'luxury'),
    ('Tonino Lamborghini', 'luxury'),
    ('Tory Burch', 'luxury'),
    ('Trump', 'daily'),
    ('Tufi Duek', 'luxury'),
    ('Uermi', 'niche'),
    ('Usher', 'daily'),
    ('Vakko', 'luxury'),
    ('Verset Parfums', 'daily'),
    ('Vertus', 'niche'),
    ('Victorinox Swiss Army', 'luxury'),
    ('Victorio Lucchino', 'luxury'),
    ('Weil', 'luxury'),
    ('Welton London', 'niche'),
    ('We Pink', 'daily'),
    ('Women Secret', 'daily'),
    ('Ys Uzac', 'niche'),
    ('Yves De Sistelle', 'daily'),
    ('Zarkoperfume', 'niche'),
    ('Zielinski Rozen', 'niche'),
    ('Zimaya', 'daily');

-- Brands from the initial curated-catalogue segmentation. They remain part of
-- the same map so a clean import receives the same assignments as an existing
-- catalogue that had already been classified by the earlier script.
INSERT INTO segment_map (brand, market_segment) VALUES
    ('aaron terence hughes', 'niche'),
    ('acqua di parma', 'niche'),
    ('alexandre j', 'niche'),
    ('amouage', 'niche'),
    ('amouroud', 'niche'),
    ('arabian oud', 'niche'),
    ('areej le dore', 'niche'),
    ('atelier cologne', 'niche'),
    ('atelier des ors', 'niche'),
    ('atkinsons', 'niche'),
    ('bdk parfums', 'niche'),
    ('boadicea the victorious', 'niche'),
    ('bohoboco', 'niche'),
    ('bois 1920', 'niche'),
    ('bond no 9', 'niche'),
    ('bon parfumeur', 'niche'),
    ('bortnikoff', 'niche'),
    ('brecourt', 'niche'),
    ('byredo', 'niche'),
    ('caron', 'niche'),
    ('carner barcelona', 'niche'),
    ('carthusia', 'niche'),
    ('clive christian', 'niche'),
    ('commodity', 'niche'),
    ('comptoir sud pacifique', 'niche'),
    ('creed', 'niche'),
    ('d orsay', 'niche'),
    ('diptyque', 'niche'),
    ('ds durga', 'niche'),
    ('eau d italie', 'niche'),
    ('electimuss', 'niche'),
    ('ellis brooklyn', 'niche'),
    ('etat libre d orange', 'niche'),
    ('evody parfums', 'niche'),
    ('ex nihilo', 'niche'),
    ('filippo sorcinelli', 'niche'),
    ('floris', 'niche'),
    ('floraiku', 'niche'),
    ('fragrance du bois', 'niche'),
    ('fragonard', 'niche'),
    ('franck boclet', 'niche'),
    ('frapin', 'niche'),
    ('frederic malle', 'niche'),
    ('fueguia 1833', 'niche'),
    ('giardino benessere', 'niche'),
    ('goutal', 'niche'),
    ('gritti', 'niche'),
    ('haute fragrance company hfc', 'niche'),
    ('histoires de parfums', 'niche'),
    ('houbigant', 'niche'),
    ('house of sillage', 'niche'),
    ('il profvmo', 'niche'),
    ('initio', 'niche'),
    ('james heeley', 'niche'),
    ('jo malone london', 'niche'),
    ('jovoy paris', 'niche'),
    ('jul et mad paris', 'niche'),
    ('juliette has a gun', 'niche'),
    ('kajal', 'niche'),
    ('kilian paris', 'niche'),
    ('l artisan parfumeur', 'niche'),
    ('laboratorio olfattivo', 'niche'),
    ('laurent mazzone parfums', 'niche'),
    ('les liquides imaginaires', 'niche'),
    ('les parfums de rosine', 'niche'),
    ('lorenzo pazzaglia', 'niche'),
    ('lorenzo villoresi', 'niche'),
    ('lubin', 'niche'),
    ('m mancera', 'niche'),
    ('m micallef', 'niche'),
    ('maison francis kurkdjian', 'niche'),
    ('maitre parfumeur et gantier', 'niche'),
    ('mancera', 'niche'),
    ('maria candida gentile', 'niche'),
    ('masque milano', 'niche'),
    ('mdci parfums', 'niche'),
    ('memo paris', 'niche'),
    ('miller harris', 'niche'),
    ('mind games', 'niche'),
    ('mizensir', 'niche'),
    ('molinard', 'niche'),
    ('mona di orio', 'niche'),
    ('monotheme venezia', 'niche'),
    ('montale', 'niche'),
    ('moresque', 'niche'),
    ('navitus parfums', 'niche'),
    ('nicolai parfumeur createur', 'niche'),
    ('nishane', 'niche'),
    ('nobile 1942', 'niche'),
    ('olfactive studio', 'niche'),
    ('ormonde jayne', 'niche'),
    ('oriza l legrand', 'niche'),
    ('parfum d empire', 'niche'),
    ('parfums de marly', 'niche'),
    ('penhaligon s', 'niche'),
    ('perris monte carlo', 'niche'),
    ('phlur', 'niche'),
    ('pierre guillaume paris', 'niche'),
    ('rance 1795', 'niche'),
    ('reminiscence', 'niche'),
    ('robert piguet', 'niche'),
    ('roja dove', 'niche'),
    ('royal crown', 'niche'),
    ('santa maria novella', 'niche'),
    ('sapientiae niche', 'niche'),
    ('serge lutens', 'niche'),
    ('shay blue london', 'niche'),
    ('sospiro perfumes', 'niche'),
    ('stephane humbert lucas 777', 'niche'),
    ('tauer perfumes', 'niche'),
    ('teo cabanel', 'niche'),
    ('thameen', 'niche'),
    ('the different company', 'niche'),
    ('the house of oud', 'niche'),
    ('the merchant of venice', 'niche'),
    ('tiziana terenzi', 'niche'),
    ('v canto', 'niche'),
    ('vilhelm parfumerie', 'niche'),
    ('widian', 'niche'),
    ('xerjoff', 'niche'),
    ('zaharoff', 'niche'),
    ('zoologist perfumes', 'niche');

INSERT INTO segment_map (brand, market_segment) VALUES
    ('adolfo dominguez', 'luxury'),
    ('alfred dunhill', 'luxury'),
    ('angel schlesser', 'luxury'),
    ('anna sui', 'luxury'),
    ('aramis', 'luxury'),
    ('azzaro', 'luxury'),
    ('balenciaga', 'luxury'),
    ('baldessarini', 'luxury'),
    ('blumarine', 'luxury'),
    ('bottega veneta', 'luxury'),
    ('boucheron', 'luxury'),
    ('burberry', 'luxury'),
    ('bvlgari', 'luxury'),
    ('cacharel', 'luxury'),
    ('calvin klein', 'luxury'),
    ('carolina herrera', 'luxury'),
    ('carven', 'luxury'),
    ('cartier', 'luxury'),
    ('cerruti', 'luxury'),
    ('chanel', 'luxury'),
    ('chloe', 'luxury'),
    ('chopard', 'luxury'),
    ('clinique', 'luxury'),
    ('coach', 'luxury'),
    ('comme des garcons', 'luxury'),
    ('costume national', 'luxury'),
    ('courreges', 'luxury'),
    ('davidoff', 'luxury'),
    ('dior', 'luxury'),
    ('dolce & gabbana', 'luxury'),
    ('donna karan', 'luxury'),
    ('dsquared2', 'luxury'),
    ('elie saab', 'luxury'),
    ('emanuel ungaro', 'luxury'),
    ('ermenegildo zegna', 'luxury'),
    ('escada', 'luxury'),
    ('estee lauder', 'luxury'),
    ('eisenberg', 'luxury'),
    ('etro', 'luxury'),
    ('fendi', 'luxury'),
    ('fresh', 'luxury'),
    ('gianfranco ferre', 'luxury'),
    ('giorgio armani', 'luxury'),
    ('giorgio beverly hills', 'luxury'),
    ('givenchy', 'luxury'),
    ('gres', 'luxury'),
    ('gucci', 'luxury'),
    ('guerlain', 'luxury'),
    ('hermes', 'luxury'),
    ('hugo boss', 'luxury'),
    ('iceberg', 'luxury'),
    ('issey miyake', 'luxury'),
    ('jean patou', 'luxury'),
    ('jean paul gaultier', 'luxury'),
    ('jesus del pozo', 'luxury'),
    ('jimmy choo', 'luxury'),
    ('joop', 'luxury'),
    ('juicy couture', 'luxury'),
    ('karl lagerfeld', 'luxury'),
    ('kayali fragrances', 'luxury'),
    ('kenzo', 'luxury'),
    ('kenneth cole', 'luxury'),
    ('korloff paris', 'luxury'),
    ('la perla', 'luxury'),
    ('lacoste fragrances', 'luxury'),
    ('lalique', 'luxury'),
    ('lancome', 'luxury'),
    ('lanvin', 'luxury'),
    ('laura biagiotti', 'luxury'),
    ('loewe', 'luxury'),
    ('lolita lempicka', 'luxury'),
    ('louis vuitton', 'luxury'),
    ('maison margiela', 'luxury'),
    ('marc jacobs', 'luxury'),
    ('mauboussin', 'luxury'),
    ('michael kors', 'luxury'),
    ('montblanc', 'luxury'),
    ('moschino', 'luxury'),
    ('mugler', 'luxury'),
    ('narciso rodriguez', 'luxury'),
    ('nina ricci', 'luxury'),
    ('oscar de la renta', 'luxury'),
    ('paco rabanne', 'luxury'),
    ('paul smith', 'luxury'),
    ('pierre balmain', 'luxury'),
    ('prada', 'luxury'),
    ('princesse marina de bourbon', 'luxury'),
    ('ralph lauren', 'luxury'),
    ('roberto cavalli', 'luxury'),
    ('rochas', 'luxury'),
    ('s t dupont', 'luxury'),
    ('salvador dali', 'luxury'),
    ('salvatore ferragamo', 'luxury'),
    ('shiseido', 'luxury'),
    ('sisley', 'luxury'),
    ('sonia rykiel', 'luxury'),
    ('ted lapidus', 'luxury'),
    ('tocca', 'luxury'),
    ('tom ford', 'luxury'),
    ('trussardi', 'luxury'),
    ('valentino', 'luxury'),
    ('van cleef arpels', 'luxury'),
    ('vera wang', 'luxury'),
    ('versace', 'luxury'),
    ('viktor rolf', 'luxury'),
    ('yohji yamamoto', 'luxury'),
    ('yves saint laurent', 'luxury'),
    ('zadig voltaire', 'luxury');

INSERT INTO segment_map (brand, market_segment) VALUES
    ('adidas', 'daily'),
    ('afnan', 'daily'),
    ('ajmal', 'daily'),
    ('al haramain perfumes', 'daily'),
    ('alexandria fragrances', 'daily'),
    ('antonio banderas', 'daily'),
    ('ard al zaafaran', 'daily'),
    ('ariana grande', 'daily'),
    ('armaf', 'daily'),
    ('avon', 'daily'),
    ('banana republic', 'daily'),
    ('bath body works', 'daily'),
    ('bentley', 'daily'),
    ('benetton', 'daily'),
    ('beyonce', 'daily'),
    ('britney spears', 'daily'),
    ('brocard', 'daily'),
    ('bruno banani', 'daily'),
    ('cafe parfums', 'daily'),
    ('christian audigier', 'daily'),
    ('christina aguilera', 'daily'),
    ('clean', 'daily'),
    ('coty', 'daily'),
    ('cuba paris', 'daily'),
    ('david beckham', 'daily'),
    ('diesel', 'daily'),
    ('dzintars', 'daily'),
    ('english laundry', 'daily'),
    ('esteban', 'daily'),
    ('eudora', 'daily'),
    ('faberlic', 'daily'),
    ('ferrari', 'daily'),
    ('franck olivier', 'daily'),
    ('ghost', 'daily'),
    ('granado', 'daily'),
    ('guess', 'daily'),
    ('halloween', 'daily'),
    ('harajuku lovers', 'daily'),
    ('hollister', 'daily'),
    ('jacomo', 'daily'),
    ('jacques bogart', 'daily'),
    ('jaguar', 'daily'),
    ('jennifer lopez', 'daily'),
    ('jeanne arthes', 'daily'),
    ('jequiti', 'daily'),
    ('kkw fragrance', 'daily'),
    ('korres', 'daily'),
    ('l erbolario', 'daily'),
    ('l occitane au bresil', 'daily'),
    ('l occitane en provence', 'daily'),
    ('la rive', 'daily'),
    ('lattafa perfumes', 'daily'),
    ('liz claiborne', 'daily'),
    ('lulu castagnette', 'daily'),
    ('lush', 'daily'),
    ('mahogany', 'daily'),
    ('maison alhambra', 'daily'),
    ('mary kay', 'daily'),
    ('masaki matsushima', 'daily'),
    ('mercedes benz', 'daily'),
    ('mexx', 'daily'),
    ('michel germain', 'daily'),
    ('naomi campbell', 'daily'),
    ('natura', 'daily'),
    ('nautica', 'daily'),
    ('o boticario', 'daily'),
    ('oriflame', 'daily'),
    ('paris elysees', 'daily'),
    ('parfums genty', 'daily'),
    ('paris hilton', 'daily'),
    ('perry ellis', 'daily'),
    ('phebo', 'daily'),
    ('playboy', 'daily'),
    ('police', 'daily'),
    ('puma', 'daily'),
    ('rasasi', 'daily'),
    ('roger gallet', 'daily'),
    ('sarah jessica parker', 'daily'),
    ('sergio tacchini', 'daily'),
    ('shakira', 'daily'),
    ('swiss arabian', 'daily'),
    ('tesori d oriente', 'daily'),
    ('the body shop', 'daily'),
    ('thera cosmeticos', 'daily'),
    ('tommy bahama', 'daily'),
    ('tommy hilfiger', 'daily'),
    ('tous', 'daily'),
    ('ulric de varens', 'daily'),
    ('victoria s secret', 'daily'),
    ('vince camuto', 'daily'),
    ('yardley', 'daily'),
    ('yves rocher', 'daily'),
    ('zara', 'daily');

UPDATE perfumes AS perfume
SET market_segment = segment_map.market_segment
FROM brands AS brand
JOIN segment_map ON lower(btrim(brand.brand)) = lower(btrim(segment_map.brand))
WHERE perfume.brand_id = brand.id
  AND (
      perfume.market_segment IS NULL
      OR perfume.market_segment = 'unclassified'
  );

COMMIT;
